version: "3"
services:
  dbt:
    image: fishtownanalytics/dbt:1.0.0
    volumes:
      - ./DBT_project:/usr/app
      - ./profiles.yml:/root/.dbt/profiles.yml
    # working_dir: /usr/app
    # command: dbt run --profiles-dir /root/.dbt --project-dir /usr/app
    ports:
      - "8080:8080"

  # Required for the tutorial
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_app
    ports:
      - "5432:5432"

  pgadmin:
    hostname: mypgadmin
    container_name: pgadmin_container2
    image: "dpage/pgadmin4:latest" # latest image as of 2021-11-08
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
